
# Autogenerated by mlir-tblgen; don't manually edit.

from ._ods_common import _cext as _ods_cext
from ._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir
_ods_cext.globals.register_traceback_file_exclusion(__file__)

import builtins
from typing import Any as _Any, Sequence as _Sequence, Union as _Union, Optional as _Optional
import sys as _sys
if _sys.version_info >= (3, 12):
  from collections.abc import Buffer as _Buffer  # pytype: disable=not-supported-yet
else:
  try:
    from typing_extensions import Buffer as _Buffer
  except ImportError:
    _Buffer = _Any


@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
  DIALECT_NAMESPACE = "brachml"

@_ods_cext.register_operation(_Dialect)
class AddOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.add"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, lhs: _ods_ir.Value, rhs: _ods_ir.Value, *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(lhs)
    operands.append(rhs)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def lhs(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def rhs(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(AddOp)
class AddOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.add"

  @builtins.property
  def lhs(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def rhs(self) -> _ods_ir.Value:
    return self.operands[1]

def add(result: _ods_ir.Type, lhs: _ods_ir.Value, rhs: _ods_ir.Value, *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return AddOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class BatchNormOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.batch_norm"

  _ODS_OPERAND_SEGMENTS = [1,0,0,1,1,]

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, running_mean: _ods_ir.Value, running_var: _ods_ir.Value, eps: _Union[float, _ods_ir.FloatAttr], *, weight: _Optional[_ods_ir.Value] = None, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    operands.append(weight)
    operands.append(bias)
    operands.append(running_mean)
    operands.append(running_var)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["eps"] = (eps if (
    isinstance(eps, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('F64Attr')) else
      _ods_ir.AttrBuilder.get('F64Attr')(eps, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def weight(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def running_mean(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 3)
    return operand_range[0]

  @builtins.property
  def running_var(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 4)
    return operand_range[0]

  @builtins.property
  def eps(self) -> _ods_ir.FloatAttr:
    return self.operation.attributes["eps"]

  @eps.setter
  def eps(self, value: _ods_ir.FloatAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["eps"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(BatchNormOp)
class BatchNormOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.batch_norm"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def weight(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 1)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def running_mean(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 3)
    return operand_range[0]

  @builtins.property
  def running_var(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 4)
    return operand_range[0]

  @builtins.property
  def eps(self) -> _ods_ir.FloatAttr:
    return self.attributes["eps"]

def batch_norm(result: _ods_ir.Type, input: _ods_ir.Value, running_mean: _ods_ir.Value, running_var: _ods_ir.Value, eps: _Union[float, _ods_ir.FloatAttr], *, weight: _Optional[_ods_ir.Value] = None, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return BatchNormOp(result=result, input=input, running_mean=running_mean, running_var=running_var, eps=eps, weight=weight, bias=bias, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ConvBnReluOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.conv_bn_relu"

  _ODS_OPERAND_SEGMENTS = [1,1,0,0,0,1,1,]

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, conv_weight: _ods_ir.Value, stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], transposed: _Union[bool, _ods_ir.BoolAttr], output_padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], groups: _Union[int, _ods_ir.IntegerAttr], running_mean: _ods_ir.Value, running_var: _ods_ir.Value, eps: _Union[float, _ods_ir.FloatAttr], *, conv_bias: _Optional[_ods_ir.Value] = None, bn_weight: _Optional[_ods_ir.Value] = None, bn_bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    operands.append(conv_weight)
    operands.append(conv_bias)
    operands.append(bn_weight)
    operands.append(bn_bias)
    operands.append(running_mean)
    operands.append(running_var)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["stride"] = (stride if (
    isinstance(stride, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(stride, context=_ods_context))
    attributes["padding"] = (padding if (
    isinstance(padding, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(padding, context=_ods_context))
    attributes["dilation"] = (dilation if (
    isinstance(dilation, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(dilation, context=_ods_context))
    attributes["transposed"] = (transposed if (
    isinstance(transposed, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('BoolAttr')) else
      _ods_ir.AttrBuilder.get('BoolAttr')(transposed, context=_ods_context))
    attributes["output_padding"] = (output_padding if (
    isinstance(output_padding, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(output_padding, context=_ods_context))
    attributes["groups"] = (groups if (
    isinstance(groups, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(groups, context=_ods_context))
    attributes["eps"] = (eps if (
    isinstance(eps, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('F64Attr')) else
      _ods_ir.AttrBuilder.get('F64Attr')(eps, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def conv_weight(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range[0]

  @builtins.property
  def conv_bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bn_weight(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 3)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bn_bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 4)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def running_mean(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 5)
    return operand_range[0]

  @builtins.property
  def running_var(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 6)
    return operand_range[0]

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["stride"]

  @stride.setter
  def stride(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["stride"] = value

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["padding"]

  @padding.setter
  def padding(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["padding"] = value

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["dilation"]

  @dilation.setter
  def dilation(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dilation"] = value

  @builtins.property
  def transposed(self) -> _ods_ir.BoolAttr:
    return self.operation.attributes["transposed"]

  @transposed.setter
  def transposed(self, value: _ods_ir.BoolAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["transposed"] = value

  @builtins.property
  def output_padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["output_padding"]

  @output_padding.setter
  def output_padding(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["output_padding"] = value

  @builtins.property
  def groups(self) -> _ods_ir.IntegerAttr:
    return self.operation.attributes["groups"]

  @groups.setter
  def groups(self, value: _ods_ir.IntegerAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["groups"] = value

  @builtins.property
  def eps(self) -> _ods_ir.FloatAttr:
    return self.operation.attributes["eps"]

  @eps.setter
  def eps(self, value: _ods_ir.FloatAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["eps"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ConvBnReluOp)
class ConvBnReluOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.conv_bn_relu"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def conv_weight(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 1)
    return operand_range[0]

  @builtins.property
  def conv_bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 2)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bn_weight(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 3)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def bn_bias(self) -> _Optional[_ods_ir.Value]:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 4)
    return operand_range[0] if len(operand_range) > 0 else None

  @builtins.property
  def running_mean(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 5)
    return operand_range[0]

  @builtins.property
  def running_var(self) -> _ods_ir.Value:
    operand_range = _ods_segmented_accessor(
         self.operands,
         self.attributes["operandSegmentSizes"], 6)
    return operand_range[0]

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["stride"]

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["padding"]

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["dilation"]

  @builtins.property
  def transposed(self) -> _ods_ir.BoolAttr:
    return self.attributes["transposed"]

  @builtins.property
  def output_padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["output_padding"]

  @builtins.property
  def groups(self) -> _ods_ir.IntegerAttr:
    return self.attributes["groups"]

  @builtins.property
  def eps(self) -> _ods_ir.FloatAttr:
    return self.attributes["eps"]

def conv_bn_relu(result: _ods_ir.Type, input: _ods_ir.Value, conv_weight: _ods_ir.Value, stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], transposed: _Union[bool, _ods_ir.BoolAttr], output_padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], groups: _Union[int, _ods_ir.IntegerAttr], running_mean: _ods_ir.Value, running_var: _ods_ir.Value, eps: _Union[float, _ods_ir.FloatAttr], *, conv_bias: _Optional[_ods_ir.Value] = None, bn_weight: _Optional[_ods_ir.Value] = None, bn_bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return ConvBnReluOp(result=result, input=input, conv_weight=conv_weight, stride=stride, padding=padding, dilation=dilation, transposed=transposed, output_padding=output_padding, groups=groups, running_mean=running_mean, running_var=running_var, eps=eps, conv_bias=conv_bias, bn_weight=bn_weight, bn_bias=bn_bias, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ConvOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.conv"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, weight: _ods_ir.Value, stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], transposed: _Union[bool, _ods_ir.BoolAttr], output_padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], groups: _Union[int, _ods_ir.IntegerAttr], *, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    operands.append(weight)
    if bias is not None: operands.append(bias)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["stride"] = (stride if (
    isinstance(stride, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(stride, context=_ods_context))
    attributes["padding"] = (padding if (
    isinstance(padding, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(padding, context=_ods_context))
    attributes["dilation"] = (dilation if (
    isinstance(dilation, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(dilation, context=_ods_context))
    attributes["transposed"] = (transposed if (
    isinstance(transposed, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('BoolAttr')) else
      _ods_ir.AttrBuilder.get('BoolAttr')(transposed, context=_ods_context))
    attributes["output_padding"] = (output_padding if (
    isinstance(output_padding, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(output_padding, context=_ods_context))
    attributes["groups"] = (groups if (
    isinstance(groups, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(groups, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def weight(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["stride"]

  @stride.setter
  def stride(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["stride"] = value

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["padding"]

  @padding.setter
  def padding(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["padding"] = value

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["dilation"]

  @dilation.setter
  def dilation(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dilation"] = value

  @builtins.property
  def transposed(self) -> _ods_ir.BoolAttr:
    return self.operation.attributes["transposed"]

  @transposed.setter
  def transposed(self, value: _ods_ir.BoolAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["transposed"] = value

  @builtins.property
  def output_padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["output_padding"]

  @output_padding.setter
  def output_padding(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["output_padding"] = value

  @builtins.property
  def groups(self) -> _ods_ir.IntegerAttr:
    return self.operation.attributes["groups"]

  @groups.setter
  def groups(self, value: _ods_ir.IntegerAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["groups"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ConvOp)
class ConvOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.conv"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def weight(self) -> _ods_ir.Value:
    return self.operands[1]

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    return None if len(self.operands) < 3 else self.operands[2]

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["stride"]

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["padding"]

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["dilation"]

  @builtins.property
  def transposed(self) -> _ods_ir.BoolAttr:
    return self.attributes["transposed"]

  @builtins.property
  def output_padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["output_padding"]

  @builtins.property
  def groups(self) -> _ods_ir.IntegerAttr:
    return self.attributes["groups"]

def conv(result: _ods_ir.Type, input: _ods_ir.Value, weight: _ods_ir.Value, stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], transposed: _Union[bool, _ods_ir.BoolAttr], output_padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], groups: _Union[int, _ods_ir.IntegerAttr], *, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return ConvOp(result=result, input=input, weight=weight, stride=stride, padding=padding, dilation=dilation, transposed=transposed, output_padding=output_padding, groups=groups, bias=bias, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LinearOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.linear"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, weight: _ods_ir.Value, *, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    operands.append(weight)
    if bias is not None: operands.append(bias)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def weight(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(LinearOp)
class LinearOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.linear"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def weight(self) -> _ods_ir.Value:
    return self.operands[1]

  @builtins.property
  def bias(self) -> _Optional[_ods_ir.Value]:
    return None if len(self.operands) < 3 else self.operands[2]

def linear(result: _ods_ir.Type, input: _ods_ir.Value, weight: _ods_ir.Value, *, bias: _Optional[_ods_ir.Value] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return LinearOp(result=result, input=input, weight=weight, bias=bias, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MatMulOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.matmul"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, lhs: _ods_ir.Value, rhs: _ods_ir.Value, *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(lhs)
    operands.append(rhs)
    _ods_context = _ods_get_default_loc_context(loc)
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def lhs(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def rhs(self) -> _ods_ir.Value:
    return self.operation.operands[1]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(MatMulOp)
class MatMulOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.matmul"

  @builtins.property
  def lhs(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def rhs(self) -> _ods_ir.Value:
    return self.operands[1]

def matmul(result: _ods_ir.Type, lhs: _ods_ir.Value, rhs: _ods_ir.Value, *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return MatMulOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MaxPool(_ods_ir.OpView):
  OPERATION_NAME = "brachml.max_pool"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, kernel_size: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], ceil_mode: _Union[bool, _ods_ir.BoolAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["kernel_size"] = (kernel_size if (
    isinstance(kernel_size, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(kernel_size, context=_ods_context))
    attributes["stride"] = (stride if (
    isinstance(stride, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(stride, context=_ods_context))
    attributes["padding"] = (padding if (
    isinstance(padding, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(padding, context=_ods_context))
    attributes["dilation"] = (dilation if (
    isinstance(dilation, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(dilation, context=_ods_context))
    attributes["ceil_mode"] = (ceil_mode if (
    isinstance(ceil_mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('BoolAttr')) else
      _ods_ir.AttrBuilder.get('BoolAttr')(ceil_mode, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def kernel_size(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["kernel_size"]

  @kernel_size.setter
  def kernel_size(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["kernel_size"] = value

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["stride"]

  @stride.setter
  def stride(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["stride"] = value

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["padding"]

  @padding.setter
  def padding(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["padding"] = value

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["dilation"]

  @dilation.setter
  def dilation(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dilation"] = value

  @builtins.property
  def ceil_mode(self) -> _ods_ir.BoolAttr:
    return self.operation.attributes["ceil_mode"]

  @ceil_mode.setter
  def ceil_mode(self, value: _ods_ir.BoolAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["ceil_mode"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(MaxPool)
class MaxPoolAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.max_pool"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def kernel_size(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["kernel_size"]

  @builtins.property
  def stride(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["stride"]

  @builtins.property
  def padding(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["padding"]

  @builtins.property
  def dilation(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["dilation"]

  @builtins.property
  def ceil_mode(self) -> _ods_ir.BoolAttr:
    return self.attributes["ceil_mode"]

def max_pool(result: _ods_ir.Type, input: _ods_ir.Value, kernel_size: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], stride: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], padding: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], dilation: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], ceil_mode: _Union[bool, _ods_ir.BoolAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return MaxPool(result=result, input=input, kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation, ceil_mode=ceil_mode, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class PermuteOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.permute"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, dims: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["dims"] = (dims if (
    isinstance(dims, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(dims, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def dims(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["dims"]

  @dims.setter
  def dims(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dims"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(PermuteOp)
class PermuteOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.permute"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def dims(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["dims"]

def permute(result: _ods_ir.Type, input: _ods_ir.Value, dims: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return PermuteOp(result=result, input=input, dims=dims, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ReLUOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.relu"

  _ODS_REGIONS = (0, True)

  def __init__(self, input: _ods_ir.Value, *, results: _Optional[_Sequence[_ods_ir.Type]] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    _ods_context = _ods_get_default_loc_context(loc)
    if results is None: results = [operands[0].type] * 1
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ReLUOp)
class ReLUOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.relu"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

def relu(input: _ods_ir.Value, *, results: _Optional[_Sequence[_ods_ir.Type]] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return ReLUOp(input=input, results=results, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class RequantOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.requant"

  _ODS_REGIONS = (0, True)

  def __init__(self, input: _ods_ir.Value, srcScale: _Union[float, _ods_ir.FloatAttr], srcZP: _Union[int, _ods_ir.IntegerAttr], dstScale: _Union[float, _ods_ir.FloatAttr], dstZP: _Union[int, _ods_ir.IntegerAttr], *, results: _Optional[_Sequence[_ods_ir.Type]] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["srcScale"] = (srcScale if (
    isinstance(srcScale, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('F32Attr')) else
      _ods_ir.AttrBuilder.get('F32Attr')(srcScale, context=_ods_context))
    attributes["srcZP"] = (srcZP if (
    isinstance(srcZP, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I32Attr')) else
      _ods_ir.AttrBuilder.get('I32Attr')(srcZP, context=_ods_context))
    attributes["dstScale"] = (dstScale if (
    isinstance(dstScale, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('F32Attr')) else
      _ods_ir.AttrBuilder.get('F32Attr')(dstScale, context=_ods_context))
    attributes["dstZP"] = (dstZP if (
    isinstance(dstZP, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I32Attr')) else
      _ods_ir.AttrBuilder.get('I32Attr')(dstZP, context=_ods_context))
    if results is None: results = [operands[0].type] * 1
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def srcScale(self) -> _ods_ir.FloatAttr:
    return self.operation.attributes["srcScale"]

  @srcScale.setter
  def srcScale(self, value: _ods_ir.FloatAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["srcScale"] = value

  @builtins.property
  def srcZP(self) -> _ods_ir.IntegerAttr:
    return self.operation.attributes["srcZP"]

  @srcZP.setter
  def srcZP(self, value: _ods_ir.IntegerAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["srcZP"] = value

  @builtins.property
  def dstScale(self) -> _ods_ir.FloatAttr:
    return self.operation.attributes["dstScale"]

  @dstScale.setter
  def dstScale(self, value: _ods_ir.FloatAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dstScale"] = value

  @builtins.property
  def dstZP(self) -> _ods_ir.IntegerAttr:
    return self.operation.attributes["dstZP"]

  @dstZP.setter
  def dstZP(self, value: _ods_ir.IntegerAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dstZP"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(RequantOp)
class RequantOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.requant"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def srcScale(self) -> _ods_ir.FloatAttr:
    return self.attributes["srcScale"]

  @builtins.property
  def srcZP(self) -> _ods_ir.IntegerAttr:
    return self.attributes["srcZP"]

  @builtins.property
  def dstScale(self) -> _ods_ir.FloatAttr:
    return self.attributes["dstScale"]

  @builtins.property
  def dstZP(self) -> _ods_ir.IntegerAttr:
    return self.attributes["dstZP"]

def requant(input: _ods_ir.Value, src_scale: _Union[float, _ods_ir.FloatAttr], src_zp: _Union[int, _ods_ir.IntegerAttr], dst_scale: _Union[float, _ods_ir.FloatAttr], dst_zp: _Union[int, _ods_ir.IntegerAttr], *, results: _Optional[_Sequence[_ods_ir.Type]] = None, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return RequantOp(input=input, srcScale=src_scale, srcZP=src_zp, dstScale=dst_scale, dstZP=dst_zp, results=results, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ReshapeOp(_ods_ir.OpView):
  OPERATION_NAME = "brachml.reshape"

  _ODS_REGIONS = (0, True)

  def __init__(self, result: _ods_ir.Type, input: _ods_ir.Value, size: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None):
    operands = []
    attributes = {}
    regions = None
    operands.append(input)
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["size"] = (size if (
    isinstance(size, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI64ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI64ArrayAttr')(size, context=_ods_context))
    results = []
    results.append(result)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operation.operands[0]

  @builtins.property
  def size(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.operation.attributes["size"]

  @size.setter
  def size(self, value: _ods_ir.DenseI64ArrayAttr):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["size"] = value

  @builtins.property
  def result(self) -> _ods_ir.OpResult:
    return self.operation.results[0]

@_ods_cext.register_op_adaptor(ReshapeOp)
class ReshapeOpAdaptor(_ods_ir.OpAdaptor):
  OPERATION_NAME = "brachml.reshape"

  @builtins.property
  def input(self) -> _ods_ir.Value:
    return self.operands[0]

  @builtins.property
  def size(self) -> _ods_ir.DenseI64ArrayAttr:
    return self.attributes["size"]

def reshape(result: _ods_ir.Type, input: _ods_ir.Value, size: _Union[_Sequence[int], _ods_ir.DenseI64ArrayAttr], *, loc: _Optional[_ods_ir.Location] = None, ip: _Optional[_ods_ir.InsertionPoint] = None) -> _ods_ir.OpResult:
  return ReshapeOp(result=result, input=input, size=size, loc=loc, ip=ip).result
